# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20170803_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('answer_message_text', models.CharField(max_length=255)),
                ('answered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='account.Account')),
            ],
            options={
                'verbose_name_plural': 'answers',
                'verbose_name': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', related_query_name='deliberation', to='account.Account')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', related_query_name='deliberation', to='discussions.Answer')),
            ],
            options={
                'verbose_name_plural': 'deliberations',
                'verbose_name': 'deliberation',
            },
        ),
    ]
