# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', related_query_name='deliberation', to='discussions.Answer'),
        ),
    ]
