# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_passwordresetconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_entrance',
            new_name='last_activity',
        ),
    ]
